version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-domain-listings"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17b3jvhg7g3up"
s3_prefix = "get-domain-listings"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

