version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-store-domain-listings"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17b3jvhg7g3up"
s3_prefix = "lambda-store-domain-listings"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

